ads_board/ads/urls.py
from django.urls import path
from .views import (
    AdvertListView,
    AdvertCreateView,
    AdvertDetailView,
    ResponseCreateView,
    ResponseDetailView,
    PrivatePageView,
    AcceptResponseView,
    DeleteResponseView,
    LikeView,
    DislikeView,
    AdvertDeleteView,
    AdvertUpdateView,
)

app_name = 'ads'

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('advert/create/', AdvertCreateView.as_view(), name='advert-create'),
    path('advert/<int:pk>/', AdvertDetailView.as_view(), name='advert-detail'),
    path('advert/<int:pk>/response/create/', ResponseCreateView.as_view(), name='response-create'),
    path('response/<int:pk>/', ResponseDetailView.as_view(), name='response-detail'),
    path('private/', PrivatePageView.as_view(), name='private'),
    path('response/accept/<int:response_id>/', AcceptResponseView.as_view(), name='accept-response'),
    path('response/delete/<int:response_id>/', DeleteResponseView.as_view(), name='delete-response'),
    path('response/<int:pk>/like/', LikeView.as_view(), name='like'),
    path('response/<int:pk>/dislike/', DislikeView.as_view(), name='dislike'),
    path('advert/<int:pk>/delete/', AdvertDeleteView.as_view(), name='delete-advert'),
    path('advert/<int:pk>/update/', AdvertUpdateView.as_view(), name='update-advert'),
]

ads_board/ads_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ads.views import AdvertListView
from ads_board import settings

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('ads/', include('ads.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads_board/users/urls.py
from django.urls import path
from .views import (
    SignUp,
    LoginView,
    LogoutView,
    PrivateProfileView,
    ResponseListView,
    ResponseDeleteView,
    ConfirmationView
)

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('private/', PrivateProfileView.as_view(), name='private'),
    path('confirmation/', ConfirmationView.as_view(), name='confirmation'),
    path('profile/responses/', ResponseListView.as_view(), name='response_list'),
    path('profile/response/<int:pk>/delete/', ResponseDeleteView.as_view(), name='delete_response'),
]

ads_board/ads/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Advert(models.Model):
    """
    Model representing an advertisement.
    """

    CATEGORY_CHOICES = [
        ('Tanks', 'Танки'),
        ('Healers', 'Хилы'),
        ('DD', 'ДД'),
        ('Merchants', 'Торговцы'),
        ('Guild Masters', 'Гилдмастеры'),
        ('Quest Givers', 'Квестгиверы'),
        ('Smiths', 'Кузнецы'),
        ('Tanner', 'Кожевники'),
        ('Potion', 'Зельевары'),
        ('Spellmasters', 'Мастера заклинаний'),
    ]

    # User who created the advertisement (User model).
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='advert')
    # Content of the advertisement.
    content = models.TextField(verbose_name="Content")
    # Title of the advertisement.
    title = models.CharField(verbose_name="Title", max_length=100)
    # Category of the advertisement.
    category = models.CharField(
        verbose_name="Category",
        max_length=20,
        choices=CATEGORY_CHOICES,
        default='Tanks'
    )
    # Text content of the response to the advertisement.
    response_text = models.TextField(blank=True)
    # Date and time of advertisement creation.
    created_at = models.DateTimeField(auto_now_add=True)
    # File upload field for the advertisement.
    upload = models.FileField(
        upload_to='uploads/',
        help_text='Upload a file',
        blank=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ads:advert-detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Advertisement'
        verbose_name_plural = 'Advertisements'


class Response(models.Model):
    """
    Model representing a response to an advertisement.
    """

    # Author of the response (User model).
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='authored_responses')
    # Related advertisement (Advert model).
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    # User who made the response (User model).
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='responses')
    # Text content of the response.
    response_text = models.TextField(verbose_name='Response text')
    # Date and time of response creation.
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    # Response acceptance status.
    status = models.BooleanField(default=False, verbose_name='Is accepted')
    # Number of likes received by the response.
    likes = models.PositiveIntegerField(default=0)
    # Number of dislikes received by the response.
    dislikes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Response from {self.user.username} to the advertisement: {self.advert.title}'

    def accept(self):
        """
        Mark the response as accepted.
        """
        self.status = True
        self.save()

    def like(self):
        """
        Increase the number of likes for the response.
        """
        self.status = True
        self.save()

    def dislike(self):
        """
        Increase the number of dislikes for the response.
        """
        self.status = False
        self.save()

    class Meta:
        permissions = [('response_create', 'Can create response')]
        verbose_name = 'Response'
        verbose_name_plural = 'Responses'

    def get_absolute_url(self):
        return reverse('ads:response-detail', kwargs={'pk': self.pk})


class Category(models.Model):
    """
    Model representing a category of advertisements.
    """

    # Name of the category.
    name = models.CharField(max_length=255, unique=True, verbose_name="Category Name")
    # Indicates if the category is an advertisement category.
    is_ad_category = models.BooleanField(default=False, verbose_name="Is Advertisement Category")
    # Many-to-many relationship field linking the category to the advertisements.
    adverts = models.ManyToManyField(Advert, related_name='categories', verbose_name="Adverts")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

ads_board/ads/forms.py
from django import forms
from ads.models import Advert


class PostForm(forms.ModelForm):
    """
    Form for creating and editing posts.
    """

    class Meta:
        model = Advert
        fields = ['title', 'category', 'content', 'upload']


class AdvertForm(forms.ModelForm):
    """
    Form for creating and editing adverts.
    """

    class Meta:
        model = Advert
        fields = ['title', 'content', 'category']
        labels = {
            'title': 'Заголовок',
            'content': 'Текст объявления',
            'category': 'Категория'
        }

ads_board/ads/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView, View

from ads_board import settings
from users.models import Profile
from .filters import AdvertFilter
from .forms import PostForm, AdvertForm
from .models import Advert, Response

from django.dispatch import Signal

# Define a signal for sending email
send_response_email_signal = Signal()


# View for the homepage
class AdvertListView(LoginRequiredMixin, ListView):
    """
    View representing the list of advertisements.
    """
    model = Advert
    ordering = '-created_at'
    template_name = 'ads/advert_list.html'
    context_object_name = 'advert_list'
    paginate_by = 15

    def get_queryset(self):
        """
        Get the queryset of advertisements, filtered by user input.
        """
        queryset = super().get_queryset()
        self.filterset = AdvertFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        """
        Get the additional context data for the template.
        """
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['is_author'] = self.request.user.groups.filter(name='authors').exists()
        return context


class AdvertCreateView(PermissionRequiredMixin, CreateView):
    """
    View for creating an advertisement.
    """
    raise_exception = True
    permission_required = 'ads.add_advert'
    form_class = PostForm
    model = Advert
    template_name = 'ads/advert_create.html'

    def form_valid(self, form):
        """
        Save the form data and send an email notification.
        """
        advert = form.save(commit=False)
        advert.user = self.request.user
        advert.author = self.request.user
        advert.save()
        form.instance.author = self.request.user
        form.instance.user = self.request.user

        # Send email
        subject = 'Новое объявление'
        message = f'Ваше объявление "{advert.title}" успешно опубликовано.'
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [self.request.user.email]
        send_mail(subject, message, from_email, recipient_list)

        return super().form_valid(form)

    def get_success_url(self):
        """
        Get the URL to redirect to after successful form submission.
        """
        return reverse('ads:advert-detail', kwargs={'pk': self.object.pk})


class AdvertDetailView(DetailView):
    """
    View representing the details of an advertisement.
    """
    model = Advert
    template_name = 'ads/advert_detail.html'


class AdvertDeleteView(DeleteView):
    """
    View for deleting an advertisement.
    """
    model = Advert
    template_name = 'ads/advert_delete.html'
    success_url = reverse_lazy('ads:advert-list')


class AdvertUpdateView(UpdateView):
    """
    View for updating an advertisement.
    """
    model = Advert
    template_name = 'ads/advert_update.html'
    form_class = AdvertForm
    success_url = reverse_lazy('ads:advert-list')


class ResponseCreateView(PermissionRequiredMixin, CreateView):
    """
    View for creating a response to an advertisement.
    """
    raise_exception = True
    permission_required = 'ads.response_create'
    model = Response
    ordering = '-created_at'
    context_object_name = 'responses'
    fields = ['response_text']
    template_name = 'ads/response_create.html'
    paginate_by = 5

    def form_valid(self, form):
        """
        Save the form data and send a signal for sending email.
        """
        form.instance.author = self.request.user
        form.instance.advert = Advert.objects.get(pk=self.kwargs['pk'])
        form.instance.user = self.request.user

        user_email = self.request.user.email
        advert_title = form.instance.advert.title
        send_response_email_signal.send(
            sender=None,
            user_email=user_email,
            advert_title=advert_title
        )

        return super().form_valid(form)


class ResponseDetailView(DetailView):
    """
    View representing the details of a response.
    """
    model = Response
    template_name = 'ads/response_detail.html'


class PrivatePageView(LoginRequiredMixin, View):
    """
    View for the private page of the user.
    """
    template_name = 'ads/private_page.html'

    def get(self, request):
        """
        Handle GET request for the private page.
        """
        user = request.user
        adverts = Advert.objects.filter(user=user)
        responses = Response.objects.filter(advert__user=user)
        is_author = Profile.objects.filter(user=user, is_author=True).exists()

        context = {
            'adverts': adverts,
            'responses': responses,
            'is_author': is_author,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        """
        Handle POST request for the private page.
        """
        user = request.user

        if not Profile.objects.filter(user=user, is_author=True).exists():
            author_group = Group.objects.get_or_create(name='authors')[0]
            user.groups.add(author_group)
            user.save()
            is_author = True
        else:
            is_author = False

        adverts = Advert.objects.filter(user=user)
        responses = Response.objects.filter(advert__user=user)

        context = {
            'adverts': adverts,
            'responses': responses,
            'is_author': is_author,
        }
        return render(request, self.template_name, context)


class AcceptResponseView(LoginRequiredMixin, View):
    """
    View for accepting a response.
    """

    def get(self, request, response_id):
        """
        Handle GET request for accepting a response.
        """
        response = get_object_or_404(Response, pk=response_id)
        response.accepted = True
        response.save()
        return redirect('ads:private')

    def post(self, request, response_id):
        """
        Handle POST request for accepting a response.
        """
        response = get_object_or_404(Response, pk=response_id)
        response.accepted = True
        response.save()
        return redirect('ads:private')


class DeleteResponseView(LoginRequiredMixin, View):
    """
    View for deleting a response.
    """

    def get(self, request, response_id):
        """
        Handle GET request for deleting a response.
        """
        response = Response.objects.get(pk=response_id)
        response.delete()
        return redirect('ads:private')

    def post(self, request, response_id):
        """
        Handle POST request for deleting a response.
        """
        try:
            response = Response.objects.get(pk=response_id)
        except Response.DoesNotExist:
            return redirect('ads:private')

        response.delete()
        return redirect('ads:private')


class LikeView(View):
    """
    View for liking a response.
    """

    def post(self, request, pk):
        """
        Handle POST request for liking a response.
        """
        response = get_object_or_404(Response, pk=pk)
        response.likes += 1
        response.save()
        return redirect('ads:advert-detail', pk=response.article.pk)


class DislikeView(View):
    def post(self, request, pk):
        response = get_object_or_404(Response, pk=pk)
        response.dislikes += 1
        response.save()
        return redirect('ads:advert-detail', pk=response.article.pk)

ads_board/ads/templates/ads/advert_create.html
{% extends 'index.html' %}
{% block title %} Написать объявление {% endblock %}
{% block content %}
  <h1>Написать объявление</h1>

  <form method="post" action="{% url 'ads:advert-create' %}"enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

ads_board/ads/templates/ads/advert_detail.html
{% extends 'index.html' %}

{% block title %}Детали объявления{% endblock %}

{% block content %}
  <h1>Детали объявления</h1>
  <h2>{{ object.title }}</h2>

  {% if object.user == request.user %}
    <form action="{% url 'ads:delete-advert' pk=object.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit">Удалить</button>
    </form>

    <form action="{% url 'ads:update-advert' pk=object.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit">Изменить</button>
    </form>
  {% endif %}

  {% if object.user != request.user %}
    <form action="{% url 'ads:response-create' pk=object.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="button">Отклик на объявление</button>
    </form>
  {% endif %}

  <p>Content: {{ object.content }}</p>
  <p>Category: {{ object.category }}</p>
  <p>Author: {{ object.user }}</p>

  {% if object.upload %}
    {% if object.media_file.url|lower|slice:'-3' == 'mp4' %}
      <video controls>
        <source src="{{ object.upload.url }}" type="video/mp4">
        Your browser does not support the video tag.
      </video>
    {% else %}
      <img src="{{ object.upload.url }}" alt="Media">
    {% endif %}
  {% endif %}
{% endblock %}

ads_board/ads/templates/ads/advert_list.html
{% extends 'index.html' %}

{% block title %}Объявления{% endblock %}

    <p>Текущее время: {{ time_now }}</p>
{% block content %}
    <h1>Объявления</h1>

    {% if advert_list %}
        <ul>
            {% for advert in advert_list %}
                <li><a href="{% url 'ads:advert-detail' pk=advert.pk %}">{{ advert.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет объявлений.</p>
    {% endif %}

    {% if is_author %}
        <p>Вы автор объявлений.</p>
    {% endif %}


    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

<!--    {{ page_obj.number }}-->

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock %}

ads_board/ads/templates/ads/advert_update.html
{% extends 'index.html' %}

{% block title %}Изменение объявления{% endblock %}

{% block content %}
  <h1>Изменение объявления</h1>

  {% if object.user == request.user %}
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сохранить изменения</button>
    </form>
  {% else %}
    <p>У вас нет прав для изменения этого объявления.</p>
  {% endif %}
{% endblock %}

ads_board/ads/templates/ads/daily_advert.html
{% extends 'index.html' %}

{% block content %}
    <h2>Здравствуй! Новые объявления за последнюю неделю!</h2>
    <ul>
        {% for advert in adverts %}
            <li><a href="{{ link }}{{ advert.get_absolute_url }}">{{ advert.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

ads_board/ads/templates/ads/private_page.html
{% extends 'index.html' %}

{% block title %}Приватная страница{% endblock %}

{% block content %}
  <h1>Приватная страница</h1>

  <h2>Информация о профиле</h2>
  <p>Имя пользователя: {{ user.username }}</p>
  <p>Email: {{ user.email }}</p>

  {% if is_author %}
    <p>Статус: Автор</p>
{% else %}
    <form method="post" action="{% url 'users:private' %}">
        {% csrf_token %}
        <button type="submit">Стать автором</button>
    </form>
{% endif %}


  <h2>Мои объявления</h2>
  <ul>
    {% for advert in adverts %}
      <li>
        <div class="advert-header">
          <a href="{% url 'ads:advert-detail' pk=advert.pk %}">{{ advert.title }}</a>
        </div>
      </li>
    {% empty %}
      <li>У вас нет объявлений.</li>
    {% endfor %}
  </ul>

  <h2>Отклики на мои объявления</h2>
  <form action="{% url 'ads:private' %}" method="GET">
    <label for="filter-advert">Фильтровать по объявлению:</label>
    <select name="filter-advert" id="filter-advert">
      <option value="">Все объявления</option>
      {% for advert in adverts %}
        <option value="{{ advert.pk }}" {% if advert.pk|slugify == selected_advert %}selected{% endif %}>{{ advert.title }}</option>
      {% endfor %}
    </select>
    <button type="submit">Применить</button>
  </form>

  <ul>
    {% for response in responses %}
      <li>
        <h3>{{ response.advert.title }}</h3>
        <p>{{ response.response_text }}</p>
        <p>Likes: {{ response.likes }}</p>
        <p>Dislikes: {{ response.dislikes }}</p>
        <form action="{% url 'ads:delete-response' response_id=response.id %}" method="POST">
          {% csrf_token %}
          <button type="submit">Удалить отклик</button>
        </form>
        {% if response.status %}
          <p>Отклик принят</p>
        {% else %}
          <form action="{% url 'ads:accept-response' response_id=response.id %}" method="POST">
            {% csrf_token %}
            <button type="submit">Принять отклик</button>
          </form>
        {% endif %}
      </li>
    {% empty %}
      <li>У вас нет откликов на объявления.</li>
    {% endfor %}
  </ul>

{% endblock %}

ads_board/ads/templates/ads/response_create.html
{% extends 'index.html' %}
{% block title %} Напишите отклик {% endblock %}
{% block content %}
  <h1>Напишите отклик</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Послать</button>
  </form>
{% endblock %}

ads_board/ads/templates/ads/response_detail.html
{% extends 'index.html' %}
{% block title %} Отклик на объявление {% endblock %}
{% block content %}
  <h1>Отклик на объявление</h1>
  <h2>Отклик от: {{ object.author }}</h2>
  <p>Текст отклика: {{ object.response_text }}</p>
  <!-- Дополнительные поля и информация об отклике -->
{% endblock %}