ads_board/accounts/urls.py
from django.urls import path
from .views import SignUp, LoginView, ProfileView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

ads_board/ads/urls.py
from django.urls import path
from .views import (
    AdvertListView,
    AdvertCreateView,
    AdvertDetailView,
    ResponseCreateView,
    ResponseDetailView,
    PrivatePageView,
    AcceptResponseView,
    DeleteResponseView,
    LikeView,
    DislikeView,
    AdvertDeleteView,
    AdvertUpdateView,
)

app_name = 'ads'

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('advert/create/', AdvertCreateView.as_view(), name='advert-create'),
    path('advert/<int:pk>/', AdvertDetailView.as_view(), name='advert-detail'),
    path('advert/<int:pk>/response/create/', ResponseCreateView.as_view(), name='response-create'),
    path('response/<int:pk>/', ResponseDetailView.as_view(), name='response-detail'),
    path('private/', PrivatePageView.as_view(), name='private'),
    path('response/accept/<int:response_id>/', AcceptResponseView.as_view(), name='accept-response'),
    path('response/delete/<int:response_id>/', DeleteResponseView.as_view(), name='delete-response'),
    path('response/<int:pk>/like/', LikeView.as_view(), name='like'),
    path('response/<int:pk>/dislike/', DislikeView.as_view(), name='dislike'),
    path('advert/<int:pk>/delete/', AdvertDeleteView.as_view(), name='delete-advert'),
    path('advert/<int:pk>/update/', AdvertUpdateView.as_view(), name='update-advert'),
]

ads_board/ads_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ads.views import AdvertListView
from ads_board import settings

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('ads/', include('ads.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads_board/accounts/views.py
from django.contrib.auth import login, logout, authenticate, get_user_model, models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.edit import CreateView

from .forms import RegistrationForm, LoginForm


class SignUp(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'accounts/signup.html'
    success_url = '/accounts/profile/'

    def form_valid(self, form):
        user = form.save()
        group = Group.objects.get_or_create(name='Пользователи')[0]
        user.groups.add(group)  # добавляем нового пользователя в эту группу
        user.save()
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        context = {
            'user': user
        }
        return render(request, 'accounts/profile.html', context)

    def post(self, request):
        user = request.user

        if not user.is_staff:
            author_group = models.Group.objects.get(name='Авторы')
            user.groups.add(author_group)
            user.is_staff = True
            user.save()

        return redirect('profile')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_staff:
                login(request, user)
                return redirect('profile')
            form.add_error(None, 'Неверные имя пользователя или пароль.')
        return render(request, 'accounts/profile.html', {'form': form})


class LogoutView(View):
    @login_required
    def get(self, request):
        logout(request)
        return redirect('accounts:login')

    def post(self, request):
        logout(request)
        return redirect('accounts:login')


@login_required
def profile(request):
    user = request.user

    if not user.groups.filter(name='Авторы').exists():
        author_group = Group.objects.get(name='Авторы')
        user.groups.add(author_group)
        user.is_author = True
        user.save()

    context = {
        'user': user
    }
    return render(request, 'accounts/profile.html', context)

ads_board/accounts/templates/accounts/login.html
{% extends 'index.html' %}
{% block title %}Вход{% endblock %}
{% block content %}
  <h1>Вход</h1>
  <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <!-- Форма входа -->
    <label for="username">Имя пользователя:</label>
    <input type="text" id="username" name="username">

    <label for="password">Пароль:</label>
    <input type="password" id="password" name="password">

    <button type="submit">Войти</button>
  </form>
{% endblock %}

ads_board/accounts/templates/accounts/logout.html
{% extends 'index.html' %}
{% block title %}Выход{% endblock %}
{% block content %}
  <h1>Выход</h1>
  <form method="post" action="{% url 'accounts:logout' %}">
    {% csrf_token %}
    <!-- Форма выхода -->
    <p>Вы уверены, что хотите выйти?</p>
    <button type="submit">Выйти</button>
  </form>
{% endblock %}

ads_board/accounts/templates/accounts/profile.html
{% extends 'index.html' %}
{% block title %}Профиль{% endblock %}
{% block content %}
  <h1>Профиль</h1>

  <h2>Информация о профиле</h2>
  <p>Имя пользователя: {{ user.username }}</p>
  <p>Email: {{ user.email }}</p>

  {% if user.is_staff %}

    <p>Статус: Автор</p>
  {% else %}
      <form method="post" action="{% url 'accounts:profile' %}">
      {% csrf_token %}
      <button type="submit">Стать автором</button>
    </form>
  {% endif %}

{% endblock %}

ads_board/accounts/templates/accounts/signup.html
<!-- signup.html -->

{% extends 'index.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h1>Регистрация</h1>
<form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}