ads_board/ads/urls.py
from django.urls import path
from .views import (
    AdvertListView,
    AdvertCreateView,
    AdvertDetailView,
    ResponseCreateView,
    ResponseDetailView,
    PrivatePageView,
    AcceptResponseView,
    DeleteResponseView,
    LikeView,
    DislikeView,
    AdvertDeleteView,
    AdvertUpdateView,
)

app_name = 'ads'

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('advert/create/', AdvertCreateView.as_view(), name='advert-create'),
    path('advert/<int:pk>/', AdvertDetailView.as_view(), name='advert-detail'),
    path('advert/<int:pk>/response/create/', ResponseCreateView.as_view(), name='response-create'),
    path('response/<int:pk>/', ResponseDetailView.as_view(), name='response-detail'),
    path('private/', PrivatePageView.as_view(), name='private'),
    path('response/accept/<int:response_id>/', AcceptResponseView.as_view(), name='accept-response'),
    path('response/delete/<int:response_id>/', DeleteResponseView.as_view(), name='delete-response'),
    path('response/<int:pk>/like/', LikeView.as_view(), name='like'),
    path('response/<int:pk>/dislike/', DislikeView.as_view(), name='dislike'),
    path('advert/<int:pk>/delete/', AdvertDeleteView.as_view(), name='delete-advert'),
    path('advert/<int:pk>/update/', AdvertUpdateView.as_view(), name='update-advert'),
]

ads_board/ads_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ads.views import AdvertListView
from ads_board import settings

urlpatterns = [
    path('', AdvertListView.as_view(), name='advert-list'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('ads/', include('ads.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads_board/users/urls.py
from django.urls import path
from .views import (
    SignUp,
    LoginView,
    LogoutView,
    PrivateProfileView,
    ResponseListView,
    ResponseDeleteView,
    ConfirmationView
)

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('private/', PrivateProfileView.as_view(), name='private'),
    path('confirmation/', ConfirmationView.as_view(), name='confirmation'),
    path('profile/responses/', ResponseListView.as_view(), name='response_list'),
    path('profile/response/<int:pk>/delete/', ResponseDeleteView.as_view(), name='delete_response'),
]

ads_board/templates/index.html
<!DOCTYPE html>
{% load static %}

{% load i18n %}
{% load tz %}

<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'admin/css/styles.css' %}" rel="stylesheet"/>

    <style>
        body {
            background-color: lightgrey;
        }

    </style>
</head>

<header>
    <a href="/ads">Все объявления</a>
    {% if user.username %}
    <a href="{% url 'users:logout' %}">Выйти</a>
    <a href="/ads/private">Приватная страница {{ user.username }}</a>
    <a href="{% url 'ads:advert-create' %}">Написать объявление</a>

    {% else %}
    <a href="{% url 'users:signup' %}">Регистрация</a>
    <a href="{% url 'users:login' %}">Войти</a>
    {% endif %}
</header>

<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-right">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
</main>

<footer>
    <div class="col-lg-12 text-center">
        <p>© 2023 Доска объявлений. All rights reserved.</p>
    </div>
</footer>
</body>
</html>